# **4MM013**

**Python Assessment 2**

Description

This assessment will allow you to demonstrate your Python programming
abilities by producing solutions to the following questions. For each
question you will need to produce evidence of the code you have created,
ideally in an IDE, and also proof of the valid output generated by
running your code. The code created should also satisfy the following
requirements:


\

● Use suitable variable and function names which, where possible, betray
the data type or function’s operation / role.

● Use comments to explain the primary operations, role, or behaviour of
your code.

● Contain a “##” title with a description, your name and student number
at the start of the program.





\


The total marks for the assessment is 15.

# Question 1  
(5 marks)  
Create a python script that will prompt the user for 9 values, checking
that they are all valid numbers, and populate those given values into a
3x3 Matrix called A.

> The program should present the created matrix , the determinant of the
> matrix and, if possible, the inverse of the matrix.
>
> The program should also present the results of the matrix operations
> A\*A and A\*A\*A  
> Finally the program should print the number of values in the matrix
> that \>= 10  
> You will need to evidence the outputs, as well as the error handling
> of any invalid values when the user attempts to input them in the
> matrix.

In [2]:
# Name : Niraj Chaudhary /  student id : 2332917
import numpy as np

def Question_1(input):
    try:
        float(input)
        return True
    except ValueError:
        return False

def valid(prompt):
    while True:
        input_value = input(prompt)
        if Question_1(input_value):
            return float(input_value)
        else:
            print("Incorrect data. Please enter a correct number.")

A = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        A[i][j] = valid("Enter a value for row " + str(i+1) + " column " + str(j+1) + ": ")

# print created matrix
print("Matrix A:")
print(A)

# print determinant of matrix
print("It is determinant of A: ", np.linalg.det(A))

# If the inverse exists, it should be printed.
if np.linalg.det(A) != 0:
    print("It is inverse of A:")
    print(np.linalg.inv(A))
else:
    print("Since A is singular, there is no inverse.")

# print AA and AA*A
print("A*A:")
print(np.dot(A,A))
print("AAA:")
print(np.dot(np.dot(A,A),A))

#count the number of matrix values that are>= 10
count = 0
for i in range(3):
    for j in range(3):
        if A[i][j] >= 10:
            count += 1
print("The number of matrix values that are >= 10: ", count)

Enter a value for row 1 column 1: 3
Enter a value for row 1 column 2: 9
Enter a value for row 1 column 3: 2
Enter a value for row 2 column 1: 3
Enter a value for row 2 column 2: 5
Enter a value for row 2 column 3: 6
Enter a value for row 3 column 1: 2
Enter a value for row 3 column 2: 3
Enter a value for row 3 column 3: 2
Matrix A:
[[3. 9. 2.]
 [3. 5. 6.]
 [2. 3. 2.]]
It is determinant of A:  27.999999999999996
It is inverse of A:
[[-0.28571429 -0.42857143  1.57142857]
 [ 0.21428571  0.07142857 -0.42857143]
 [-0.03571429  0.32142857 -0.42857143]]
A*A:
[[40. 78. 64.]
 [36. 70. 48.]
 [19. 39. 26.]]
AAA:
[[482. 942. 676.]
 [414. 818. 588.]
 [226. 444. 324.]]
The number of matrix values that are >= 10:  0


# Question 2

(5 marks)

Write and test a Python function, that makes use of numpy, to return the
sum of the elements on the main diagonal (upper left to lower right) of
a square matrix. In linear algebra, this value is called the trace of
the matrix.

> For example, with a matrix represented as a list of lists eg. \[\[9,
> 8, 7\], \[6, 5, 4\], \[3, 2, 1\]\], your function should return (9 +
> 5 + 1) = “15”
>
> Your Python function solution should work for any sized square matrix
> passed to it. Demonstrate that this is the case with 3x3, 4x4, and 6x6
> matrix examples.

In [5]:
# Name : Niraj Chaudhary /  student id : 2332917
import numpy as np

def Question_2():
    """
  Requests a square matrix from the user and computes its trace using numpy.
    """
    n = int(input("Enter the square matrix's size.: "))
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            value = int(input(f"Enter a value for row {i+1}, column {j+1}: "))
            row.append(value)
        matrix.append(row)
    matrix = np.array(matrix) # Transform the input into a numpy array.
    trace = np.trace(matrix) # Use numpy to compute the trace.
    return trace
print("Enter the values of the  matrix:")
traced = Question_2()
print(f"The trace of the given matrix is: {traced}")

Enter the values of the  matrix:
Enter the square matrix's size.: 3
Enter a value for row 1, column 1: 1
Enter a value for row 1, column 2: 2
Enter a value for row 1, column 3: 3
Enter a value for row 2, column 1: 4
Enter a value for row 2, column 2: 5
Enter a value for row 2, column 3: 6
Enter a value for row 3, column 1: 7
Enter a value for row 3, column 2: 8
Enter a value for row 3, column 3: 9
The trace of the given matrix is: 15


# Question 3

(5 marks)  
Ackermann's function (A) is defined as:

> *A(m,n):*  
> *n+1, if m=0*  
> *A(m-1,1), if m\>0 and n=0*  
> *A(m-1,A(m,n-1)), if m\>0 and n\> 0*
>
> Write a recursive Python function to implement Ackermann's function.
> How many recursive calls will be required to evaluate A(2,3)?

In [7]:
# Name : Niraj Chaudhary /  student id : 2332917
def Question_3(m, n):
    if m == 0:
        return n + 1
    elif m > 0 and n == 0:
        return Question_3(m - 1, 1)
    elif m > 0 and n > 0:
        return Question_3(m - 1, Question_3(m, n - 1))
result = Question_3(2, 3)
print(result)
def Question_3(m, n, count=0):
    if m == 0:
        count += 1
        return n + 1, count
    elif m > 0 and n == 0:
        count += 1
        return Question_3(m - 1, 1, count)
    elif m > 0 and n > 0:
        res1, count1 = Question_3(m, n - 1, count + 1)
        res2, count2 = Question_3(m - 1, res1, count1)
        count = count2
        return res2, count

result, num_calls = Question_3(2, 3)
print("Result:", result)
print("Number of recursive calls:", num_calls -1)

9
Result: 9
Number of recursive calls: 43
